import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from '@/components/ui/tooltip'
import { Outfit } from 'next/font/google'

const outFit = Outfit({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${outFit.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
