import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from '@/components/ui/tooltip'
import { Outfit } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Provider from "./_src/_provider/Provider";
import { Toaster } from "@/components/ui/sonner";

const outFit = Outfit({ subsets: ['latin'] })
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html
                lang="en"
                className={` ${outFit.className} h-full antialiased`} suppressHydrationWarning cz-shortcut-listen="true">
                <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
                    <Toaster />
                    <Provider>
                        <TooltipProvider>{children}</TooltipProvider>
                    </Provider>
                </body>
            </html>
        </ClerkProvider>
    );
}
